name: Rubocop

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install gems
      run: |
        gem install bundler -v "2.4.22"
        bundle install --jobs 4 --retry 3
    - name: Run checks
      run: rubocop -F --fail-level C -f s
