name: Rubocop

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build
      run: |
        gem install bundler -v ">= 1.10"
        gem install rubocop
    - name: Run tests
      run: rubocop -F --fail-level C -f s
