name: Rubocop

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: Install gems
      run: |
        gem update --system
        gem install bundler -v ">= 1.10"
        gem install rubocop -v "1.12"
    - name: Run checks
      run: rubocop -F --fail-level C -f s
